import { executeStatements, id, json, text } from "./helpers.js";

export async function up(connection) {
  await executeStatements(connection, [
    `create table if not exists ai_interactions (
      id ${id} primary key,
      user_id ${id} not null,
      report_id ${id} null,
      type varchar(80) not null,
      prompt ${text} null,
      response ${json} null,
      model varchar(120) null,
      used_for_learning boolean not null default false,
      safety_flags ${json} null,
      feedback_rating int null,
      feedback_comment ${text} null,
      created_at datetime not null default current_timestamp,
      index idx_ai_interactions_user (user_id, created_at),
      index idx_ai_interactions_report (report_id, created_at)
    )`,
    `create table if not exists medical_documents (
      id ${id} primary key,
      source varchar(120) not null,
      title varchar(500) not null,
      url varchar(900) null,
      content ${text} null,
      content_hash varchar(128) null unique,
      metadata ${json} null,
      created_at datetime not null default current_timestamp,
      unique key uq_medical_documents_url (url(500))
    )`,
    `create table if not exists medical_chunks (
      id ${id} primary key,
      document_id ${id} not null,
      chunk_text ${text} not null,
      embedding ${json} null,
      source varchar(120) null,
      url varchar(900) null,
      created_at datetime not null default current_timestamp,
      index idx_medical_chunks_document (document_id)
    )`,
    `create table if not exists ai_usage_logs (
      id ${id} primary key,
      user_id ${id} not null,
      endpoint varchar(120) null,
      feature_type varchar(80) not null,
      tokens_used int not null default 0,
      prompt_tokens int not null default 0,
      response_tokens int not null default 0,
      input_tokens int not null default 0,
      output_tokens int not null default 0,
      estimated_cost decimal(12,6) not null default 0,
      cost_estimate decimal(12,6) not null default 0,
      cost_ngn decimal(14,4) not null default 0,
      model_used varchar(120) null,
      request_id varchar(120) not null,
      prompt_hash varchar(128) null,
      response_time int null,
      response_time_ms int null,
      cache_hit boolean not null default false,
      blocked_reason varchar(160) null,
      status varchar(40) not null default 'completed',
      safety_flags ${json} null,
      metadata ${json} null,
      created_at datetime not null default current_timestamp,
      index idx_ai_usage_user_feature_created (user_id, feature_type, created_at),
      index idx_ai_usage_feature_created (feature_type, created_at)
    )`,
    `create table if not exists user_ai_quotas (
      id ${id} primary key,
      user_id ${id} not null,
      plan_code varchar(80) null,
      monthly_budget_ngn decimal(14,4) not null default 0,
      monthly_cost_limit_ngn decimal(14,4) not null default 0,
      monthly_token_limit int null,
      daily_request_limit int not null default 0,
      burst_per_minute int null,
      per_minute_limit int not null default 0,
      burst_limit int not null default 0,
      period_start date not null,
      period_end date not null,
      created_at datetime not null default current_timestamp,
      updated_at datetime not null default current_timestamp on update current_timestamp,
      unique key uq_user_ai_quotas_period (user_id, period_start)
    )`,
    `create table if not exists ai_budget_limits (
      id ${id} primary key,
      scope varchar(40) not null,
      scope_key varchar(120) not null,
      monthly_budget_ngn decimal(14,4) not null default 0,
      monthly_cost_limit_ngn decimal(14,4) not null default 0,
      emergency_throttle boolean not null default false,
      active boolean not null default true,
      created_at datetime not null default current_timestamp,
      unique key uq_ai_budget_scope (scope, scope_key)
    )`,
    `create table if not exists ai_cache_store (
      id ${id} primary key,
      cache_key varchar(128) not null unique,
      feature_type varchar(80) not null,
      prompt_hash varchar(128) null,
      model_used varchar(120) null,
      response_text ${text} not null,
      metadata ${json} null,
      hits int not null default 0,
      expires_at datetime not null,
      last_hit_at datetime null,
      created_at datetime not null default current_timestamp
    )`,
    `create table if not exists ai_cost_summary (
      id ${id} primary key,
      user_id ${id} null,
      feature_type varchar(80) not null,
      model_used varchar(120) null,
      period_start date not null,
      period_end date not null,
      cost_ngn decimal(14,4) not null default 0,
      tokens_used int not null default 0,
      input_tokens int not null default 0,
      output_tokens int not null default 0,
      requests int not null default 0,
      cache_hits int not null default 0,
      blocked_requests int not null default 0,
      average_response_time_ms int not null default 0,
      updated_at datetime not null default current_timestamp on update current_timestamp,
      unique key uq_ai_cost_summary_feature_model (period_start, feature_type, model_used),
      index idx_ai_cost_summary_user (user_id, feature_type, period_start)
    )`
  ]);
}
