export const eventTypes = {
  USER_REGISTERED: "USER_REGISTERED",
  EMAIL_VERIFICATION_REQUESTED: "EMAIL_VERIFICATION_REQUESTED",
  USER_LOGIN_NEW_DEVICE: "USER_LOGIN_NEW_DEVICE",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  LOGIN_FAILED_MULTIPLE: "LOGIN_FAILED_MULTIPLE",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",

  AI_REPORT_ANALYZED: "AI_REPORT_ANALYZED",
  AI_CRITICAL_HEALTH_FLAG: "AI_CRITICAL_HEALTH_FLAG",
  AI_WEEKLY_SUMMARY: "AI_WEEKLY_SUMMARY",

  DOCTOR_ASSIGNED: "DOCTOR_ASSIGNED",
  DOCTOR_RESPONSE_RECEIVED: "DOCTOR_RESPONSE_RECEIVED",
  APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_REMINDER: "APPOINTMENT_REMINDER",

  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  SUBSCRIPTION_ACTIVATED: "SUBSCRIPTION_ACTIVATED",
  SUBSCRIPTION_RENEWAL: "SUBSCRIPTION_RENEWAL",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  REFUND_PROCESSED: "REFUND_PROCESSED",

  COUPON_APPLIED: "COUPON_APPLIED",
  COUPON_EXPIRING_SOON: "COUPON_EXPIRING_SOON",

  TRIAL_STARTED: "TRIAL_STARTED",
  TRIAL_EXPIRING_SOON: "TRIAL_EXPIRING_SOON",
  TRIAL_EXPIRED: "TRIAL_EXPIRED",

  NEW_DOCTOR_APPLICATION: "NEW_DOCTOR_APPLICATION",
  DOCTOR_VERIFIED: "DOCTOR_VERIFIED",
  HIGH_AI_COST_ALERT: "HIGH_AI_COST_ALERT",
  SYSTEM_ERROR_ALERT: "SYSTEM_ERROR_ALERT",
  DB_STORAGE_WARNING: "DB_STORAGE_WARNING",

  WEEKLY_USAGE_REPORT: "WEEKLY_USAGE_REPORT",
  INACTIVITY_REMINDER: "INACTIVITY_REMINDER",
  MILESTONE_REACHED: "MILESTONE_REACHED",

  CONSENT_UPDATED: "CONSENT_UPDATED",
  DATA_ACCESS_LOGGED: "DATA_ACCESS_LOGGED",
  MEDICAL_DISCLAIMER_SENT: "MEDICAL_DISCLAIMER_SENT"
};

export const adminEventTypes = new Set([
  eventTypes.NEW_DOCTOR_APPLICATION,
  eventTypes.HIGH_AI_COST_ALERT,
  eventTypes.SYSTEM_ERROR_ALERT,
  eventTypes.DB_STORAGE_WARNING,
  eventTypes.LOGIN_FAILED_MULTIPLE,
  eventTypes.ACCOUNT_LOCKED,
  eventTypes.PAYMENT_SUCCESS,
  eventTypes.PAYMENT_FAILED,
  eventTypes.REFUND_PROCESSED
]);
